name: Deploy to CPanel

on:
  push:
    branches:
      - main  # Adjust this if your default branch is not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to CPanel via SFTP
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: '-avz --delete'
          path: ./build/
          remote_path: /home/boilermakercrt/public_html/
          remote_host: ${{ secrets.SFTP_ADDRESS }}
          remote_user: ${{ secrets.FTP_USER }}
          remote_key: ${{ secrets.SFTP_KEY }}  
